# -*- coding: utf-8 -*-

test_todos = {'grocery shopping': {'Eggs': 'done',
                                   'Bacon': 'done',
                                   'Bread': 'done',
                                   'Halibut': 'deferred',
                                   'Coffee beans online order': 'in progress',
                                   'Ribeye Steak': 'deferred',
                                   'Peanut Butter': 'pending'},
              'house cleaning': {'Dusting': 'done',
                                 'Mopping': 'pending',
                                 'Trash': 'pending',
                                 'Washing Dishes': 'done'},
              'global warming blog post': {'Sea level rates research': 'pending',
                                           'Effect of volcanic eruptions research': 'pending',
                                           'Tahiti reefs research': 'deferred',
                                           'New York harbor projection': 'in progress',
                                           'Iceland archeologic record research': 'done'},
              'office redesign': {'1st Meeting with architect': 'done',
                                  'Initial floorplan': 'done',
                                  'Hiring carpenters': 'done',
                                  'Cabinet selection': 'done',
                                  'Flooring installation': 'in progress',
                                  'Assessment of half-height partition': 'done',
                                  'Assessment of all-glass partition': 'abandoned',
                                  '2nd Meeting with architect': 'pending',
                                  '3rd Meeting with architect': 'pending',
                                  'Final Meeting with architect': 'pending'},
              'hard drive cleanup': {'Move photos to external Seagate drive': 'pending',
                                     'Move sound files to external Seagate drive': 'pending',
                                     'Have Aperture relocate original photos': 'done'},
              'home repair': {'Re-enamel sink': 'abandoned',
                              'Replace kitchen floorboards': 'done',
                              'Caulk windows in back bedroom': 'pending',
                              'Repaint garage': 'deferred',
                              'Clean gutters': 'done'}}
